;; RUN: %pscm_cc --test %s | FileCheck %s

;; Test vector conversion functions

;; Test vector->list
;; CHECK: (dah dah didah)
(vector->list '#(dah dah didah))
;; CHECK-NEXT: ()
(vector->list '#())
;; CHECK-NEXT: (a b c)
(vector->list '#(a b c))
;; CHECK-NEXT: (1 2 3)
(vector->list '#(1 2 3))
;; CHECK-NEXT: (#t #f)
(vector->list '#(#t #f))
;; CHECK-NEXT: ("hello" "world")
(vector->list '#("hello" "world"))
;; CHECK-NEXT: (a 1 "test" #t)
(vector->list '#(a 1 "test" #t))
;; CHECK-NEXT: ((a b) (c d))
(vector->list '#((a b) (c d)))
;; CHECK-NEXT: (#(a) #(b) #(c))
(vector->list '#(#(a) #(b) #(c)))

;; Test list->vector
;; CHECK: #(dididit dah)
(list->vector '(dididit dah))
;; CHECK-NEXT: #()
(list->vector '())
;; CHECK-NEXT: #(a b c)
(list->vector '(a b c))
;; CHECK-NEXT: #(1 2 3)
(list->vector '(1 2 3))
;; CHECK-NEXT: #(#t #f)
(list->vector '(#t #f))
;; CHECK-NEXT: #("hello" "world")
(list->vector '("hello" "world"))
;; CHECK-NEXT: #(a 1 "test" #t)
(list->vector '(a 1 "test" #t))
;; CHECK-NEXT: #((a b) (c d))
(list->vector '((a b) (c d)))
;; CHECK-NEXT: #(#(a) #(b) #(c))
(list->vector '(#(a) #(b) #(c)))

;; Test round-trip conversion
;; CHECK: #(a b c)
(list->vector (vector->list '#(a b c)))
;; CHECK-NEXT: (a b c)
(vector->list (list->vector '(a b c)))
;; CHECK-NEXT: #()
(list->vector (vector->list '#()))
;; CHECK-NEXT: ()
(vector->list (list->vector '()))
;; CHECK-NEXT: #(1 2 3 4 5)
(list->vector (vector->list '#(1 2 3 4 5)))
;; CHECK-NEXT: (1 2 3 4 5)
(vector->list (list->vector '(1 2 3 4 5)))
;; CHECK-NEXT: #(a b c d e)
(list->vector (vector->list '#(a b c d e)))
;; CHECK-NEXT: (a b c d e)
(vector->list (list->vector '(a b c d e)))

;; Test with make-vector
;; CHECK: (none none none)
(vector->list (make-vector 3))
;; CHECK-NEXT: (hi hi hi)
(vector->list (make-vector 3 'hi))
;; CHECK-NEXT: (0 1 2)
(vector->list (let ((v (make-vector 3)))
                (vector-set! v 0 0)
                (vector-set! v 1 1)
                (vector-set! v 2 2)
                v))

;; Test with vector function
;; CHECK: (a b c)
(vector->list (vector 'a 'b 'c))
;; CHECK-NEXT: #(x y z)
(list->vector '(x y z))
;; CHECK-NEXT: (1 2 3 4 5)
(vector->list (vector 1 2 3 4 5))
;; CHECK-NEXT: #(foo bar baz)
(list->vector '(foo bar baz))

;; Test with nested structures
;; CHECK: ((a b) (c d))
(vector->list '#((a b) (c d)))
;; CHECK-NEXT: #((1 2) (3 4))
(list->vector '((1 2) (3 4)))
;; CHECK-NEXT: (#(a) #(b) #(c))
(vector->list '#(#(a) #(b) #(c)))
;; CHECK-NEXT: #(#(1) #(2) #(3))
(list->vector '(#(1) #(2) #(3)))

