name: Linux Vau

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_vau_with_pscm:
    strategy:
      matrix:
        mode: [ Debug ]
    runs-on: [ ubuntu-22.04 ]

    steps:
      - uses: actions/checkout@v3

      - name: deps
        run: |
          sudo apt install ghostscript

      - name: Clone Deps
        run: git submodule update --init
        working-directory: ${{github.workspace}}

      - name: Clone Vau
        run: git clone https://github.com/PikachuHy/vau.git -b vau_pscm
        working-directory: ${{github.workspace}}/..

      - name: Use pscm
        run: ln -s ${{github.workspace}} pscm
        working-directory: ${{github.workspace}}/..

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.mode}}

      - name: Configure CMake
        run: CXX=clang++ CC=clang cmake -S ${{github.workspace}}/../vau -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.mode}} -G Ninja -DUSE_CCACHE=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.mode}} -j --verbose

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: TEXMACS_PATH=${{github.workspace}}/../vau/resource PSCM_LOAD_PATH=${{github.workspace}}/../vau/resource/progs ./Vau

      - name: Check ps file
        working-directory: ${{github.workspace}}/build
        run: ls -lha

      - name: Convert to pdf
        working-directory: ${{github.workspace}}/build
        run: ps2pdf vau-test.ps

      - name: Check output pdf
        working-directory: ${{github.workspace}}/build
        run: |
          ls -lha
          ls -la vau-test.pdf2 | cut -d ' ' -f 8

      - name: Check pdf size
        working-directory: ${{github.workspace}}/build
        run: bash ${{github.workspace}}/../vau/check.sh

      
