name: Linux GCC (xmake)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_with_gcc:
    strategy:
      matrix:
        gcc_version: [ 10, 11, 12 ]
        mode: [ Release, Debug ]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: deps
        run: |
          sudo apt install -y build-essential
          sudo apt install -y gcc-${{matrix.gcc_version}} g++-${{matrix.gcc_version}}

      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/build/.build_cache
            /home/runner/.config/.xmake
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
    
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.7.7
          actions-cache-folder: '.xmake-cache'

      - name: Build
        run: |
          xmake config --yes --mode=${{matrix.mode}} --cc=gcc-${{matrix.gcc_version}} --cxx=g++-${{matrix.gcc_version}}
          xmake build --jobs=8

      - name: Test
        run: xmake run --group=tests
