name: MacOS (xmake)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_with_xmake_on_macos:
    runs-on: macos-12
    strategy:
      matrix:
        mode: [ Release, Debug ]

    steps:
      - uses: actions/checkout@v3

      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/build/.build_cache
            /Users/runner/.xmake
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
          
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.7.7
          actions-cache-folder: '.xmake-cache'

      - name: Build
        run: |
          xmake config --yes --mode=${{matrix.mode}}
          xmake build --jobs=8

      - name: Test
        run: xmake run --group=tests

